[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false
padding = { x = 5, y = 5 }
opacity = 0.8
decorations = "None"

[font]
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 13

[colors.primary]
foreground = "#d6d7d4"
background = "#282a36"

[colors.normal]
green = "#05DB70"
blue = "#65BAD3"
magenta = "#ED00A4"
